apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: optimus-frame

resources:
  - ../base

# Para atualizar a tag via CI/CD:
#   kustomize edit set image ghcr.io/stack-food/optimus-frame-transform=ghcr.io/stack-food/dev-optimus-frame-transform:<SHA>
images:
  - name: ghcr.io/stack-food/optimus-frame-transform
    newName: ghcr.io/stack-food/dev-optimus-frame-transform
    newTag: latest

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: optimus-transform-worker
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: optimus-transform-config
