apiVersion: v1
kind: ConfigMap
metadata:
  name: optimus-transform-config
data:
  RabbitMQ__HostName: "rabbitmq.messaging.svc.cluster.local"
  RabbitMQ__PrefetchCount: "1"
  Storage__BucketName: "optimus-frame-core-bucket-dev"
  DOTNET_ENVIRONMENT: "Development"
